const colors = {
  fire: "#FDDFDF",
  grass: "#DEFDE0",
  electric: "#FCF7DE",
  water: "#DEF3FD",
  ground: "#f4e7da",
  rock: "#d5d5d4",
  fairy: "#fceaff",
  poison: "#c098d777", //"#98d7a5",//
  bug: "#f8d5a3",
  dragon: "#97b3e6",
  psychic: "#c50d724b", //"#eaeda1",//
  flying: "#F5F5F5",
  fighting: "#E6E0D4",
  normal: "#F5F5F5",
};

const pokemons = [
  {
    // https://assets.pokemon.com/assets/cms2/img/pokedex/full/ //
    id: 1,
    name: "bulbasaur",
    type: { name: "grass", url: "https://pokeapi.co/api/v2/type/12/" },
    height: 7,
    weight: 69,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png",
  },
  {
    id: 2,
    name: "ivysaur",
    type: { name: "grass", url: "https://pokeapi.co/api/v2/type/12/" },
    height: 10,
    weight: 130,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png",
  },
  {
    id: 3,
    name: "venusaur",
    type: { name: "grass", url: "https://pokeapi.co/api/v2/type/12/" },
    height: 20,
    weight: 1000,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png",
  },
  {
    id: 4,
    name: "charmander",
    type: { name: "fire", url: "https://pokeapi.co/api/v2/type/10/" },
    height: 6,
    weight: 85,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png",
  },
  {
    id: 5,
    name: "charmeleon",
    type: { name: "fire", url: "https://pokeapi.co/api/v2/type/10/" },
    height: 11,
    weight: 190,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png",
  },
  {
    id: 6,
    name: "charizard",
    type: { name: "fire", url: "https://pokeapi.co/api/v2/type/10/" },
    height: 17,
    weight: 905,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png",
  },
  {
    id: 7,
    name: "squirtle",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 5,
    weight: 90,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png",
  },
  {
    id: 8,
    name: "wartortle",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 10,
    weight: 225,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png",
  },
  {
    id: 9,
    name: "blastoise",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 16,
    weight: 855,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png",
  },
  {
    id: 10,
    name: "caterpie",
    type: { name: "bug", url: "https://pokeapi.co/api/v2/type/7/" },
    height: 3,
    weight: 29,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png",
  },
  {
    id: 11,
    name: "metapod",
    type: { name: "bug", url: "https://pokeapi.co/api/v2/type/7/" },
    height: 7,
    weight: 99,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png",
  },
  {
    id: 12,
    name: "butterfree",
    type: { name: "bug", url: "https://pokeapi.co/api/v2/type/7/" },
    height: 11,
    weight: 320,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png",
  },
  {
    id: 13,
    name: "weedle",
    type: { name: "bug", url: "https://pokeapi.co/api/v2/type/7/" },
    height: 3,
    weight: 32,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png",
  },
  {
    id: 14,
    name: "kakuna",
    type: { name: "bug", url: "https://pokeapi.co/api/v2/type/7/" },
    height: 6,
    weight: 100,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png",
  },
  {
    id: 15,
    name: "beedrill",
    type: { name: "bug", url: "https://pokeapi.co/api/v2/type/7/" },
    height: 10,
    weight: 295,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png",
  },
  {
    id: 16,
    name: "pidgey",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 3,
    weight: 18,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png",
  },
  {
    id: 17,
    name: "pidgeotto",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 11,
    weight: 300,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png",
  },
  {
    id: 18,
    name: "pidgeot",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 15,
    weight: 395,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png",
  },
  {
    id: 19,
    name: "rattata",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 3,
    weight: 35,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png",
  },
  {
    id: 20,
    name: "raticate",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 7,
    weight: 185,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png",
  },
  {
    id: 21,
    name: "spearow",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 3,
    weight: 20,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png",
  },
  {
    id: 22,
    name: "fearow",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 12,
    weight: 380,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png",
  },
  {
    id: 23,
    name: "ekans",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 20,
    weight: 69,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png",
  },
  {
    id: 24,
    name: "arbok",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 35,
    weight: 650,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png",
  },
  {
    id: 25,
    name: "pikachu",
    type: { name: "electric", url: "https://pokeapi.co/api/v2/type/13/" },
    height: 4,
    weight: 60,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png",
  },
  {
    id: 26,
    name: "raichu",
    type: { name: "electric", url: "https://pokeapi.co/api/v2/type/13/" },
    height: 8,
    weight: 300,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png",
  },
  {
    id: 27,
    name: "sandshrew",
    type: { name: "ground", url: "https://pokeapi.co/api/v2/type/5/" },
    height: 6,
    weight: 120,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png",
  },
  {
    id: 28,
    name: "sandslash",
    type: { name: "ground", url: "https://pokeapi.co/api/v2/type/5/" },
    height: 10,
    weight: 295,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png",
  },
  {
    id: 29,
    name: "nidoran-f",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 4,
    weight: 70,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/029.png",
  },
  {
    id: 30,
    name: "nidorina",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 8,
    weight: 200,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/030.png",
  },
  {
    id: 31,
    name: "nidoqueen",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 13,
    weight: 600,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/031.png",
  },
  {
    id: 32,
    name: "nidoran-m",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 5,
    weight: 90,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png",
  },
  {
    id: 33,
    name: "nidorino",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 9,
    weight: 195,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png",
  },
  {
    id: 34,
    name: "nidoking",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 14,
    weight: 620,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png",
  },
  {
    id: 35,
    name: "clefairy",
    type: { name: "fairy", url: "https://pokeapi.co/api/v2/type/18/" },
    height: 6,
    weight: 75,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png",
  },
  {
    id: 36,
    name: "clefable",
    type: { name: "fairy", url: "https://pokeapi.co/api/v2/type/18/" },
    height: 13,
    weight: 400,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png",
  },
  {
    id: 37,
    name: "vulpix",
    type: { name: "fire", url: "https://pokeapi.co/api/v2/type/10/" },
    height: 6,
    weight: 99,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/037.png",
  },
  {
    id: 38,
    name: "ninetales",
    type: { name: "fire", url: "https://pokeapi.co/api/v2/type/10/" },
    height: 11,
    weight: 199,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/038.png",
  },
  {
    id: 39,
    name: "jigglypuff",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 5,
    weight: 55,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png",
  },
  {
    id: 40,
    name: "wigglytuff",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 10,
    weight: 120,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/040.png",
  },
  {
    id: 41,
    name: "zubat",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 8,
    weight: 75,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/041.png",
  },
  {
    id: 42,
    name: "golbat",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 16,
    weight: 550,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/042.png",
  },
  {
    id: 43,
    name: "oddish",
    type: { name: "grass", url: "https://pokeapi.co/api/v2/type/12/" },
    height: 5,
    weight: 54,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/043.png",
  },
  {
    id: 44,
    name: "gloom",
    type: { name: "grass", url: "https://pokeapi.co/api/v2/type/12/" },
    height: 8,
    weight: 86,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/044.png",
  },
  {
    id: 45,
    name: "vileplume",
    type: { name: "grass", url: "https://pokeapi.co/api/v2/type/12/" },
    height: 12,
    weight: 186,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/045.png",
  },
  {
    id: 46,
    name: "paras",
    type: { name: "bug", url: "https://pokeapi.co/api/v2/type/7/" },
    height: 3,
    weight: 54,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/046.png",
  },
  {
    id: 47,
    name: "parasect",
    type: { name: "bug", url: "https://pokeapi.co/api/v2/type/7/" },
    height: 10,
    weight: 295,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/047.png",
  },
  {
    id: 48,
    name: "venonat",
    type: { name: "bug", url: "https://pokeapi.co/api/v2/type/7/" },
    height: 10,
    weight: 300,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/048.png",
  },
  {
    id: 49,
    name: "venomoth",
    type: { name: "bug", url: "https://pokeapi.co/api/v2/type/7/" },
    height: 15,
    weight: 125,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/049.png",
  },
  {
    id: 50,
    name: "diglett",
    type: { name: "ground", url: "https://pokeapi.co/api/v2/type/5/" },
    height: 2,
    weight: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/050.png",
  },
  {
    id: 51,
    name: "dugtrio",
    type: { name: "ground", url: "https://pokeapi.co/api/v2/type/5/" },
    height: 7,
    weight: 333,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/051.png",
  },
  {
    id: 52,
    name: "meowth",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 4,
    weight: 42,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/052.png",
  },
  {
    id: 53,
    name: "persian",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 10,
    weight: 320,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/053.png",
  },
  {
    id: 54,
    name: "psyduck",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 8,
    weight: 196,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png",
  },
  {
    id: 55,
    name: "golduck",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 17,
    weight: 766,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/055.png",
  },
  {
    id: 56,
    name: "mankey",
    type: { name: "fighting", url: "https://pokeapi.co/api/v2/type/2/" },
    height: 5,
    weight: 280,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/056.png",
  },
  {
    id: 57,
    name: "primeape",
    type: { name: "fighting", url: "https://pokeapi.co/api/v2/type/2/" },
    height: 10,
    weight: 320,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/057.png",
  },
  {
    id: 58,
    name: "growlithe",
    type: { name: "fire", url: "https://pokeapi.co/api/v2/type/10/" },
    height: 7,
    weight: 190,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/058.png",
  },
  {
    id: 59,
    name: "arcanine",
    type: { name: "fire", url: "https://pokeapi.co/api/v2/type/10/" },
    height: 19,
    weight: 1550,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/059.png",
  },
  {
    id: 60,
    name: "poliwag",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 6,
    weight: 124,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/060.png",
  },
  {
    id: 61,
    name: "poliwhirl",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 10,
    weight: 200,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/061.png",
  },
  {
    id: 62,
    name: "poliwrath",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 13,
    weight: 540,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/062.png",
  },
  {
    id: 63,
    name: "abra",
    type: { name: "psychic", url: "https://pokeapi.co/api/v2/type/14/" },
    height: 9,
    weight: 195,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/063.png",
  },
  {
    id: 64,
    name: "kadabra",
    type: { name: "psychic", url: "https://pokeapi.co/api/v2/type/14/" },
    height: 13,
    weight: 565,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/064.png",
  },
  {
    id: 65,
    name: "alakazam",
    type: { name: "psychic", url: "https://pokeapi.co/api/v2/type/14/" },
    height: 15,
    weight: 480,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/065.png",
  },
  {
    id: 66,
    name: "machop",
    type: { name: "fighting", url: "https://pokeapi.co/api/v2/type/2/" },
    height: 8,
    weight: 195,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/066.png",
  },
  {
    id: 67,
    name: "machoke",
    type: { name: "fighting", url: "https://pokeapi.co/api/v2/type/2/" },
    height: 15,
    weight: 705,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/067.png",
  },
  {
    id: 68,
    name: "machamp",
    type: { name: "fighting", url: "https://pokeapi.co/api/v2/type/2/" },
    height: 16,
    weight: 1300,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/068.png",
  },
  {
    id: 69,
    name: "bellsprout",
    type: { name: "grass", url: "https://pokeapi.co/api/v2/type/12/" },
    height: 7,
    weight: 40,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/069.png",
  },
  {
    id: 70,
    name: "weepinbell",
    type: { name: "grass", url: "https://pokeapi.co/api/v2/type/12/" },
    height: 10,
    weight: 64,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/070.png",
  },
  {
    id: 71,
    name: "victreebel",
    type: { name: "grass", url: "https://pokeapi.co/api/v2/type/12/" },
    height: 17,
    weight: 155,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/071.png",
  },
  {
    id: 72,
    name: "tentacool",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 9,
    weight: 455,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/072.png",
  },
  {
    id: 73,
    name: "tentacruel",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 16,
    weight: 550,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/073.png",
  },
  {
    id: 74,
    name: "geodude",
    type: { name: "rock", url: "https://pokeapi.co/api/v2/type/6/" },
    height: 4,
    weight: 200,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/074.png",
  },
  {
    id: 75,
    name: "graveler",
    type: { name: "rock", url: "https://pokeapi.co/api/v2/type/6/" },
    height: 10,
    weight: 1050,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/075.png",
  },
  {
    id: 76,
    name: "golem",
    type: { name: "rock", url: "https://pokeapi.co/api/v2/type/6/" },
    height: 14,
    weight: 3000,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/076.png",
  },
  {
    id: 77,
    name: "ponyta",
    type: { name: "fire", url: "https://pokeapi.co/api/v2/type/10/" },
    height: 10,
    weight: 300,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/077.png",
  },
  {
    id: 78,
    name: "rapidash",
    type: { name: "fire", url: "https://pokeapi.co/api/v2/type/10/" },
    height: 17,
    weight: 950,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/078.png",
  },
  {
    id: 79,
    name: "slowpoke",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 12,
    weight: 360,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/079.png",
  },
  {
    id: 80,
    name: "slowbro",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 16,
    weight: 785,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/080.png",
  },
  {
    id: 81,
    name: "magnemite",
    type: { name: "electric", url: "https://pokeapi.co/api/v2/type/13/" },
    height: 3,
    weight: 60,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/081.png",
  },
  {
    id: 82,
    name: "magneton",
    type: { name: "electric", url: "https://pokeapi.co/api/v2/type/13/" },
    height: 10,
    weight: 600,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/082.png",
  },
  {
    id: 83,
    name: "farfetchd",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 8,
    weight: 150,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/083.png",
  },
  {
    id: 84,
    name: "doduo",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 14,
    weight: 392,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/084.png",
  },
  {
    id: 85,
    name: "dodrio",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 18,
    weight: 852,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/085.png",
  },
  {
    id: 86,
    name: "seel",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 11,
    weight: 900,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/086.png",
  },
  {
    id: 87,
    name: "dewgong",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 17,
    weight: 1200,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/087.png",
  },
  {
    id: 88,
    name: "grimer",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 9,
    weight: 300,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/088.png",
  },
  {
    id: 89,
    name: "muk",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 12,
    weight: 300,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/089.png",
  },
  {
    id: 90,
    name: "shellder",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 3,
    weight: 40,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/090.png",
  },
  {
    id: 91,
    name: "cloyster",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 15,
    weight: 1325,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/091.png",
  },
  {
    id: 92,
    name: "gastly",
    type: { name: "ghost", url: "https://pokeapi.co/api/v2/type/8/" },
    height: 13,
    weight: 1,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/092.png",
  },
  {
    id: 93,
    name: "haunter",
    type: { name: "ghost", url: "https://pokeapi.co/api/v2/type/8/" },
    height: 16,
    weight: 1,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/093.png",
  },
  {
    id: 94,
    name: "gengar",
    type: { name: "ghost", url: "https://pokeapi.co/api/v2/type/8/" },
    height: 15,
    weight: 405,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/094.png",
  },
  {
    id: 95,
    name: "onix",
    type: { name: "rock", url: "https://pokeapi.co/api/v2/type/6/" },
    height: 88,
    weight: 2100,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/095.png",
  },
  {
    id: 96,
    name: "drowzee",
    type: { name: "psychic", url: "https://pokeapi.co/api/v2/type/14/" },
    height: 10,
    weight: 324,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/096.png",
  },
  {
    id: 97,
    name: "hypno",
    type: { name: "psychic", url: "https://pokeapi.co/api/v2/type/14/" },
    height: 16,
    weight: 756,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/097.png",
  },
  {
    id: 98,
    name: "krabby",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 4,
    weight: 65,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/098.png",
  },
  {
    id: 99,
    name: "kingler",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 13,
    weight: 600,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/099.png",
  },
  {
    id: 100,
    name: "voltorb",
    type: { name: "electric", url: "https://pokeapi.co/api/v2/type/13/" },
    height: 5,
    weight: 104,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/100.png",
  },
  {
    id: 101,
    name: "electrode",
    type: { name: "electric", url: "https://pokeapi.co/api/v2/type/13/" },
    height: 12,
    weight: 666,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/101.png",
  },
  {
    id: 102,
    name: "exeggcute",
    type: { name: "grass", url: "https://pokeapi.co/api/v2/type/12/" },
    height: 4,
    weight: 25,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/102.png",
  },
  {
    id: 103,
    name: "exeggutor",
    type: { name: "grass", url: "https://pokeapi.co/api/v2/type/12/" },
    height: 20,
    weight: 1200,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/103.png",
  },
  {
    id: 104,
    name: "cubone",
    type: { name: "ground", url: "https://pokeapi.co/api/v2/type/5/" },
    height: 4,
    weight: 65,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/104.png",
  },
  {
    id: 105,
    name: "marowak",
    type: { name: "ground", url: "https://pokeapi.co/api/v2/type/5/" },
    height: 10,
    weight: 450,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/105.png",
  },
  {
    id: 106,
    name: "hitmonlee",
    type: { name: "fighting", url: "https://pokeapi.co/api/v2/type/2/" },
    height: 15,
    weight: 498,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/106.png",
  },
  {
    id: 107,
    name: "hitmonchan",
    type: { name: "fighting", url: "https://pokeapi.co/api/v2/type/2/" },
    height: 14,
    weight: 502,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/107.png",
  },
  {
    id: 108,
    name: "lickitung",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 12,
    weight: 655,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/108.png",
  },
  {
    id: 109,
    name: "koffing",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 6,
    weight: 10,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/109.png",
  },
  {
    id: 110,
    name: "weezing",
    type: { name: "poison", url: "https://pokeapi.co/api/v2/type/4/" },
    height: 12,
    weight: 95,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/110.png",
  },
  {
    id: 111,
    name: "rhyhorn",
    type: { name: "ground", url: "https://pokeapi.co/api/v2/type/5/" },
    height: 10,
    weight: 1150,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/111.png",
  },
  {
    id: 112,
    name: "rhydon",
    type: { name: "ground", url: "https://pokeapi.co/api/v2/type/5/" },
    height: 19,
    weight: 1200,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/112.png",
  },
  {
    id: 113,
    name: "chansey",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 11,
    weight: 346,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/113.png",
  },
  {
    id: 114,
    name: "tangela",
    type: { name: "grass", url: "https://pokeapi.co/api/v2/type/12/" },
    height: 10,
    weight: 350,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/114.png",
  },
  {
    id: 115,
    name: "kangaskhan",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 22,
    weight: 800,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/115.png",
  },
  {
    id: 116,
    name: "horsea",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 4,
    weight: 80,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/116.png",
  },
  {
    id: 117,
    name: "seadra",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 12,
    weight: 250,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/117.png",
  },
  {
    id: 118,
    name: "goldeen",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 6,
    weight: 150,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/118.png",
  },
  {
    id: 119,
    name: "seaking",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 13,
    weight: 390,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/119.png",
  },
  {
    id: 120,
    name: "staryu",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 8,
    weight: 345,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/120.png",
  },
  {
    id: 121,
    name: "starmie",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 11,
    weight: 800,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/121.png",
  },
  {
    id: 122,
    name: "mr-mime",
    type: { name: "psychic", url: "https://pokeapi.co/api/v2/type/14/" },
    height: 13,
    weight: 545,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/122.png",
  },
  {
    id: 123,
    name: "scyther",
    type: { name: "bug", url: "https://pokeapi.co/api/v2/type/7/" },
    height: 15,
    weight: 560,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/123.png",
  },
  {
    id: 124,
    name: "jynx",
    type: { name: "ice", url: "https://pokeapi.co/api/v2/type/15/" },
    height: 14,
    weight: 406,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/124.png",
  },
  {
    id: 125,
    name: "electabuzz",
    type: { name: "electric", url: "https://pokeapi.co/api/v2/type/13/" },
    height: 11,
    weight: 300,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/125.png",
  },
  {
    id: 126,
    name: "magmar",
    type: { name: "fire", url: "https://pokeapi.co/api/v2/type/10/" },
    height: 13,
    weight: 445,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/126.png",
  },
  {
    id: 127,
    name: "pinsir",
    type: { name: "bug", url: "https://pokeapi.co/api/v2/type/7/" },
    height: 15,
    weight: 550,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/127.png",
  },
  {
    id: 128,
    name: "tauros",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 14,
    weight: 884,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/128.png",
  },
  {
    id: 129,
    name: "magikarp",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 9,
    weight: 100,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/129.png",
  },
  {
    id: 130,
    name: "gyarados",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 65,
    weight: 2350,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/130.png",
  },
  {
    id: 131,
    name: "lapras",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 25,
    weight: 2200,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/131.png",
  },
  {
    id: 132,
    name: "ditto",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 3,
    weight: 40,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/132.png",
  },
  {
    id: 133,
    name: "eevee",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 3,
    weight: 65,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/133.png",
  },
  {
    id: 134,
    name: "vaporeon",
    type: { name: "water", url: "https://pokeapi.co/api/v2/type/11/" },
    height: 10,
    weight: 290,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/134.png",
  },
  {
    id: 135,
    name: "jolteon",
    type: { name: "electric", url: "https://pokeapi.co/api/v2/type/13/" },
    height: 8,
    weight: 245,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/135.png",
  },
  {
    id: 136,
    name: "flareon",
    type: { name: "fire", url: "https://pokeapi.co/api/v2/type/10/" },
    height: 9,
    weight: 250,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/136.png",
  },
  {
    id: 137,
    name: "porygon",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 8,
    weight: 365,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/137.png",
  },
  {
    id: 138,
    name: "omanyte",
    type: { name: "rock", url: "https://pokeapi.co/api/v2/type/6/" },
    height: 4,
    weight: 75,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/138.png",
  },
  {
    id: 139,
    name: "omastar",
    type: { name: "rock", url: "https://pokeapi.co/api/v2/type/6/" },
    height: 10,
    weight: 350,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/139.png",
  },
  {
    id: 140,
    name: "kabuto",
    type: { name: "rock", url: "https://pokeapi.co/api/v2/type/6/" },
    height: 5,
    weight: 115,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/140.png",
  },
  {
    id: 141,
    name: "kabutops",
    type: { name: "rock", url: "https://pokeapi.co/api/v2/type/6/" },
    height: 13,
    weight: 405,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/141.png",
  },
  {
    id: 142,
    name: "aerodactyl",
    type: { name: "rock", url: "https://pokeapi.co/api/v2/type/6/" },
    height: 18,
    weight: 590,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/142.png",
  },
  {
    id: 143,
    name: "snorlax",
    type: { name: "normal", url: "https://pokeapi.co/api/v2/type/1/" },
    height: 21,
    weight: 4600,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/143.png",
  },
  {
    id: 144,
    name: "articuno",
    type: { name: "ice", url: "https://pokeapi.co/api/v2/type/15/" },
    height: 17,
    weight: 554,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/144.png",
  },
  {
    id: 145,
    name: "zapdos",
    type: { name: "electric", url: "https://pokeapi.co/api/v2/type/13/" },
    height: 16,
    weight: 526,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/145.png",
  },
  {
    id: 146,
    name: "moltres",
    type: { name: "fire", url: "https://pokeapi.co/api/v2/type/10/" },
    height: 20,
    weight: 600,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/146.png",
  },
  {
    id: 147,
    name: "dratini",
    type: { name: "dragon", url: "https://pokeapi.co/api/v2/type/16/" },
    height: 18,
    weight: 33,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/147.png",
  },
  {
    id: 148,
    name: "dragonair",
    type: { name: "dragon", url: "https://pokeapi.co/api/v2/type/16/" },
    height: 40,
    weight: 165,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/148.png",
  },
  {
    id: 149,
    name: "dragonite",
    type: { name: "dragon", url: "https://pokeapi.co/api/v2/type/16/" },
    height: 22,
    weight: 2100,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png",
  },
  {
    id: 150,
    name: "mewtwo",
    type: { name: "psychic", url: "https://pokeapi.co/api/v2/type/14/" },
    height: 20,
    weight: 1220,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png",
  },
  {
    id: 151,
    name: "mew",
    type: { name: "psychic", url: "https://pokeapi.co/api/v2/type/14/" },
    height: 4,
    weight: 40,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/151.png",
  },
];
